let tableGrid = '<table class="dei-grid my-3" data-toggle="tooltip">\n';
tableGrid += '  <thead>\n';
tableGrid += '    <tr>\n';
tableGrid += '      <th></th>\n';
tableGrid += '      <th scope="col">Very Easy</th>\n';
tableGrid += '      <th scope="col">Moderately Easy</th>\n';
tableGrid += '      <th scope="col">Neither Easy Nor Difficult</th>\n';
tableGrid += '      <th scope="col">Moderately Difficult</th>\n';
tableGrid += '      <th scope="col">Very Difficult</th>\n';
tableGrid += '    </tr>\n';
tableGrid += '  </thead>\n';
tableGrid += '  <tbody>\n';
tableGrid += '    <tr>\n';
tableGrid += '      <th scope="row">Extremely Important</th>\n';
tableGrid += '      <td class="one-one"></td>\n';
tableGrid += '      <td class="one-two"></td>\n';
tableGrid += '      <td class="one-three"></td>\n';
tableGrid += '      <td class="one-four"></td>\n';
tableGrid += '      <td class="one-five"></td>\n';
tableGrid += '    </tr>\n';
tableGrid += '    <tr>\n';
tableGrid += '      <th scope="row">Very Important</th>\n';
tableGrid += '      <td class="two-one"></td>\n';
tableGrid += '      <td class="two-two"></td>\n';
tableGrid += '      <td class="two-three"></td>\n';
tableGrid += '      <td class="two-four"></td>\n';
tableGrid += '      <td class="two-five"></td>\n';
tableGrid += '    </tr>\n';
tableGrid += '    <tr>\n';
tableGrid += '      <th scope="row">Moderately Importance</th>\n';
tableGrid += '      <td class="three-one"></td>\n';
tableGrid += '      <td class="three-two"></td>\n';
tableGrid += '      <td class="three-three"></td>\n';
tableGrid += '      <td class="three-four"></td>\n';
tableGrid += '      <td class="three-five"></td>\n';
tableGrid += '    </tr>\n';
tableGrid += '    <tr>\n';
tableGrid += '      <th scope="row">Slightly Important</th>\n';
tableGrid += '      <td class="four-one"></td>\n';
tableGrid += '      <td class="four-two"></td>\n';
tableGrid += '      <td class="four-three"></td>\n';
tableGrid += '      <td class="four-four"></td>\n';
tableGrid += '      <td class="four-five"></td>\n';
tableGrid += '    </tr>\n';
tableGrid += '    <tr>\n';
tableGrid += '      <th scope="row">Not At All Important</th>\n';
tableGrid += '      <td class="five-one"></td>\n';
tableGrid += '      <td class="five-two"></td>\n';
tableGrid += '      <td class="five-three"></td>\n';
tableGrid += '      <td class="five-four"></td>\n';
tableGrid += '      <td class="five-five"></td>\n';
tableGrid += '    </tr>\n';
tableGrid += '  </tbody>\n';
tableGrid += '</table>\n';
